service: marked
frameworkVersion: "3"
useDotenv: true

provider:
   name: aws
   runtime: nodejs16.x
   stage: dev
   region: ap-south-1
   timeout: 10

functions:
   rest:
      handler: src/server.handler
      events:
         - http: ANY /{proxy+}
         - http: ANY /

      environment:
         DATABASE_URL: ${env:DATABASE_URL}
         JWT_SECRET: ${env:JWT_SECRET}

plugins:
   - serverless-plugin-typescript
   - serverless-plugin-monorepo

# only include the Prisma binary required on AWS Lambda while packaging
package:
   patterns:
      - "!node_modules/.prisma/client/libquery_engine-*"
      - "node_modules/.prisma/client/libquery_engine-rhel-*"
      - "!node_modules/prisma/libquery_engine-*"
      - "!node_modules/@prisma/engines/**"
